import { burgerButton } from './burger-button.js';
import { filterBar } from './filter-bar.js';
import { tabBar } from './tab.js';
import { sumeRest } from './sume-rest.js';
import { notify } from './notify.js';
import { form } from './form.js';
import { renderCkeditor } from './ckeditor.js';
import{ renderFaqs } from './faqs.js';
import{ imageContent } from './image-content.js';
import{ product } from './product.js';
import { menu } from './menu.js';
import { menuCategory } from './menu-category.js';
import { menuFilter } from './menu-filter.js';
import { cart } from './cart.js';
import { checkout } from './checkout.js';
import { purchase } from './purchase.js';


burgerButton();
filterBar();
tabBar();
sumeRest();
notify();
form();
renderCkeditor();
renderFaqs();
imageContent();
product();
menu();
menuCategory();
menuFilter();
cart();
checkout();
purchase();
